[project]
name = "freecad-tools"
version = "0.1.0"
description = ""
dependencies = [
    "PyYAML",
    "lib3mf==2.5.0",
]

[project.optional-dependencies]
dev = [
    "pylint",
    "yamllint",
    "black",
    "isort",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
