#!/usr/bin/env python3
"""
variant_array_assignment.py - FreeCAD macro to assign configuration variants to array elements.

This macro:
1. Reads configuration names from a spreadsheet (generated by generate_variant_configs.py)
2. Resizes an array to accommodate all configurations
3. Assigns each configuration to an array element

Usage:
    1. Open a FreeCAD document with a parametric array
    2. Run generate_variant_configs.py first to create the configuration spreadsheet
    3. Run this macro via Macro > Execute macro or Macro > Macros...
    4. Enter configuration when prompted
"""

import math
import sys
from pathlib import Path

import FreeCAD

# Add parent directory to path to import macro_helper
macro_dir = Path(__file__).parent
if str(macro_dir) not in sys.path:
    sys.path.insert(0, str(macro_dir))

try:
    from macro_helper import (
        get_object_by_identifier,
        load_or_prompt_config,
    )
except ImportError as e:
    print(f"Error importing macro_helper: {e}")
    print("Make sure macro_helper.py is in the same directory as this macro.")
    sys.exit(1)


def get_object_by_user_label(doc, user_label):
    """Legacy helper function - use get_object_by_identifier instead."""
    return get_object_by_identifier(doc, user_label)


def apply_configs_to_array(config=None):
    """
    Apply configuration variants to array elements.

    Args:
        config: Optional configuration dictionary with keys:
            - spreadsheet_label: Name of the spreadsheet with configs
            - array_label: Name of the array object
    """
    doc = FreeCAD.ActiveDocument
    if not doc:
        print("No active document found.")
        return

    # Use provided config or use defaults
    if config is None:
        config = {
            "spreadsheet_label": "VariantData",
            "array_label": "VariantTestArray",
        }

    spreadsheet_label = config.get("spreadsheet_label", "VariantData")
    array_label = config.get("array_label", "VariantTestArray")

    # Retrieve objects by User Label
    spreadsheet = get_object_by_user_label(doc, spreadsheet_label)
    array = get_object_by_user_label(doc, array_label)

    if not spreadsheet:
        print(f"Error: Spreadsheet with user label '{spreadsheet_label}' not found.")
        return
    if not array:
        print(f"Error: Array with user label '{array_label}' not found.")
        return

    # --- 2. GET THE COUNT OF CONFIGS (STARTING AT ROW 2) ---
    configs = []
    current_row = 2  # Start at line 2 (Line 1 is the header)

    while True:
        cell_location = f"A{current_row}"

        try:
            # This will throw a ValueError if the cell is completely uninitialized/empty
            cell_value = spreadsheet.get(cell_location)
        except ValueError:
            # We hit an uninitialized cell, meaning we reached the end of the data
            break
        except Exception as e:
            print(f"Stopped reading spreadsheet at {cell_location} due to unexpected error: {e}")
            break

        # Stop searching when an empty string or None is encountered
        # (in case the cell was initialized/formatted but left blank)
        if cell_value is None or str(cell_value).strip() == "":
            break

        configs.append(str(cell_value).strip())
        current_row += 1

    num_configs = len(configs)

    if num_configs == 0:
        print("No configurations found in column A starting from row 2.")
        return

    print(f"Found {num_configs} configurations: {configs}")

    # --- 3. RESIZE THE ORTHO ARRAY ---
    # Calculate grid size (e.g. 9 -> 3x3, 10 -> 4x3)
    grid_size_x = math.ceil(math.sqrt(num_configs))
    grid_size_y = math.ceil(num_configs / grid_size_x)

    # Apply to Draft Ortho Arrays or Link Arrays
    # It tries the standard properties FreeCAD uses for X/Y counts
    if hasattr(array, "NumberX"):
        array.NumberX = grid_size_x
        array.NumberY = grid_size_y
        if hasattr(array, "NumberZ"):
            array.NumberZ = 1
    elif hasattr(array, "CountX"):  # Common in Link Branch
        array.CountX = grid_size_x
        array.CountY = grid_size_y
        if hasattr(array, "CountZ"):
            array.CountZ = 1
    elif hasattr(array, "XQuantity"):
        array.XQuantity = grid_size_x
        array.YQuantity = grid_size_y
        if hasattr(array, "ZQuantity"):
            array.ZQuantity = 1

    # Recompute to ensure the array generates/updates the children Link objects
    # based on the new dimension numbers before we try assigning things to them.
    doc.recompute()

    # --- 4. FIND ARRAY ELEMENTS AND APPLY CONFIGS ---
    base_object = getattr(array, "Base", getattr(array, "Source", None))

    # Collect the individual link elements generated by the array
    array_elements = []

    # Check if elements are standard children/group items (Most common for LinkArrays / LinkGroups)
    if hasattr(array, "OutList"):
        for child in array.OutList:
            # We want to grab the array children but NOT the base original object
            if base_object and child.Name == base_object.Name:
                continue
            array_elements.append(child)

    # Fallback if the elements are stored in a Group property
    elif hasattr(array, "Group"):
        for child in array.Group:
            if base_object and child.Name == base_object.Name:
                continue
            array_elements.append(child)

    if len(array_elements) < num_configs:
        print(f"Warning: Found {len(array_elements)} array elements, but have {num_configs} configurations.")
        print("The array might not be fully generating independent child Links.")

    # --- FORCE ENUMERATION REFRESH ---
    # First, mark the "config" property of all elements as Touched
    for element in array_elements:
        if hasattr(element, "config"):
            try:
                element.setPropertyStatus("config", "Touched")
            except Exception:
                pass

    # Recompute the document so FreeCAD rebuilds the valid Enum list internally
    doc.recompute()

    # Assign each found element a config string
    for i, config_name in enumerate(configs):
        if i >= len(array_elements):
            break

        element = array_elements[i]

        # 4a. Enable Copy-on-Write so properties can be overridden without modifying the base
        if hasattr(element, "LinkCopyOnChange"):
            element.LinkCopyOnChange = "Enabled"  # standard value in Link branch/FeaturePython links

        # An alternative way copy-on-write is sometimes handled in properties:
        try:
            element.setPropertyStatus("config", "CopyOnChange")
        except Exception:
            pass

        # 4b. Assign the "config" property
        if hasattr(element, "config"):
            element.config = config_name
            print(f"Assigned config '{config_name}' to element: {element.Label}")
        else:
            print(f"Element {element.Label} does not have a property named 'config'.")

    # Final recompute to apply the configuration visual/structural changes
    doc.recompute()
    print("Array update complete.")


def main():
    """Main entry point - can be called with or without configuration."""
    doc = FreeCAD.ActiveDocument
    if not doc:
        print("No active document.")
        return

    # Check if a config file exists in the document's directory
    doc_path = Path(doc.FileName) if hasattr(doc, "FileName") and doc.FileName else None
    config_path = None
    if doc_path:
        config_dir = doc_path.parent
        config_path = config_dir / ".freecad_tools" / "macro_config.yml"

    # Define dialog fields for user configuration
    dialog_fields = [
        {
            "name": "spreadsheet_label",
            "type": "text",
            "label": "Spreadsheet Name:",
            "default": "VariantData",
            "help": "Name of the spreadsheet containing configurations",
        },
        {
            "name": "array_label",
            "type": "text",
            "label": "Array Name:",
            "default": "VariantTestArray",
            "help": "Name of the array to configure",
        },
    ]

    # Load or prompt for configuration
    config = load_or_prompt_config(
        str(config_path) if config_path else ".freecad_tools/macro_config.yml",
        dialog_fields=dialog_fields,
        dialog_title="Apply Variant Configurations to Array",
    )

    if config:
        apply_configs_to_array(config=config)


# Run the macro
if __name__ == "__main__":
    main()
else:
    # When called via Macro menu, run main directly
    main()
