#!/usr/bin/env python3
"""
variant_array_assignment.py - FreeCAD macro to assign configuration variants to array elements.

This macro:
1. Reads configuration names from a spreadsheet (generated by generate_variant_configs.py)
2. Resizes an array to accommodate all configurations
3. Assigns each configuration to an array element

Usage:
    1. Open a FreeCAD document with a parametric array
    2. Run generate_variant_configs.py first to create the configuration spreadsheet
    3. Run this macro via Macro > Execute macro or Macro > Macros...
    4. Enter configuration when prompted
"""

import math
import sys
from pathlib import Path

import FreeCAD

MANAGED_COPY_GROUP_PROPERTY = "FreeCADToolsManagedCopyOnChange"
ARRAY_NAME_PROPERTY = "FreeCADToolsArrayName"
ARRAY_LABEL_PROPERTY = "FreeCADToolsArrayLabel"

# Add parent directory to path to import macro_helper
macro_dir = Path(__file__).parent
if str(macro_dir) not in sys.path:
    sys.path.insert(0, str(macro_dir))

try:
    from macro_helper import (
        get_object_by_identifier,
        load_or_prompt_config,
    )
except ImportError as e:
    print(f"Error importing macro_helper: {e}")
    print("Make sure macro_helper.py is in the same directory as this macro.")
    sys.exit(1)


def get_object_by_user_label(doc, user_label):
    """Legacy helper function - use get_object_by_identifier instead."""
    return get_object_by_identifier(doc, user_label)


def normalize_config_name(config_name):
    """Normalize spreadsheet string values to FreeCAD configuration names."""
    return str(config_name).strip().lstrip("'")


def get_array_base_object(array):
    """Return the source/base object used by common FreeCAD array types."""
    return getattr(array, "Base", getattr(array, "Source", None))


def set_array_dimensions(array, x_count, y_count, z_count=1):
    """Set dimensions on supported FreeCAD array variants."""
    if hasattr(array, "NumberX"):
        array.NumberX = x_count
        array.NumberY = y_count
        if hasattr(array, "NumberZ"):
            array.NumberZ = z_count
        return True

    if hasattr(array, "CountX"):
        array.CountX = x_count
        array.CountY = y_count
        if hasattr(array, "CountZ"):
            array.CountZ = z_count
        return True

    if hasattr(array, "XQuantity"):
        array.XQuantity = x_count
        array.YQuantity = y_count
        if hasattr(array, "ZQuantity"):
            array.ZQuantity = z_count
        return True

    return False


def get_array_elements(array):
    """Return generated array elements, excluding the base/source object."""
    base_object = get_array_base_object(array)
    candidates = []

    if hasattr(array, "OutList"):
        candidates = list(array.OutList)

    if not candidates and hasattr(array, "Group"):
        candidates = list(array.Group)

    elements = []
    for child in candidates:
        if base_object and child.Name == base_object.Name:
            continue
        elements.append(child)

    return elements


def clear_config_override(element):
    """Best-effort cleanup of config Copy-on-Write state on surviving elements."""
    if hasattr(element, "config"):
        for status in ("-CopyOnChange", "-Touched"):
            try:
                element.setPropertyStatus("config", status)
            except Exception:
                pass

    if hasattr(element, "LinkCopyOnChange"):
        try:
            element.LinkCopyOnChange = "Disabled"
        except Exception:
            pass


def get_property_value(obj, property_name):
    """Return a FreeCAD property value from either an attribute or property lookup."""
    if hasattr(obj, property_name):
        return getattr(obj, property_name)

    if hasattr(obj, "getPropertyByName"):
        try:
            return obj.getPropertyByName(property_name)
        except Exception:
            return None

    return None


def set_freecad_property(obj, property_name, value, property_type="String"):
    """Set a FreeCAD object property, adding it first when possible."""
    if not hasattr(obj, property_name) and hasattr(obj, "addProperty"):
        try:
            obj.addProperty(f"App::Property{property_type}", property_name, "freecad_tools", "Managed by freecad_tools")
        except Exception:
            try:
                obj.addProperty(f"App::Property{property_type}", property_name)
            except Exception:
                pass

    try:
        setattr(obj, property_name, value)
        return True
    except Exception:
        return False


def is_hidden(obj):
    """Return True when an object is hidden in the FreeCAD tree/view."""
    view_object = getattr(obj, "ViewObject", None)
    if view_object is not None and hasattr(view_object, "Visibility"):
        return not bool(view_object.Visibility)

    visibility = get_property_value(obj, "Visibility")
    if visibility is not None:
        return not bool(visibility)

    return False


def is_auto_delete_link(obj):
    """Return True for FreeCAD link mode values equivalent to Auto Delete."""
    link_mode = get_property_value(obj, "LinkMode")
    if link_mode is None:
        return False

    normalized = str(link_mode).replace(" ", "").replace("_", "").replace("-", "").lower()
    return normalized == "autodelete"


def is_copy_on_change_group(obj):
    """Return True for hidden groups FreeCAD creates for Copy-on-Write links."""
    identifiers = [
        getattr(obj, "Name", ""),
        getattr(obj, "Label", ""),
        getattr(obj, "TypeId", ""),
    ]
    return any("copyonchangegroup" in str(identifier).replace(" ", "").lower() for identifier in identifiers)


def get_document_objects(doc):
    """Return document objects when available."""
    return list(getattr(doc, "Objects", []))


def copy_group_matches_array(obj, array):
    """Return True when a tagged CopyOnChangeGroup belongs to the target array."""
    if not bool(get_property_value(obj, MANAGED_COPY_GROUP_PROPERTY)):
        return False

    array_name = getattr(array, "Name", None)
    array_label = getattr(array, "Label", None)
    tagged_array_name = get_property_value(obj, ARRAY_NAME_PROPERTY)
    tagged_array_label = get_property_value(obj, ARRAY_LABEL_PROPERTY)

    return bool((array_name and tagged_array_name == array_name) or (array_label and tagged_array_label == array_label))


def tag_copy_on_change_group(obj, array):
    """Tag a CopyOnChangeGroup so future cleanups can identify ownership."""
    tagged = set_freecad_property(obj, MANAGED_COPY_GROUP_PROPERTY, True, "Bool")
    tagged = set_freecad_property(obj, ARRAY_NAME_PROPERTY, getattr(array, "Name", ""), "String") and tagged
    tagged = set_freecad_property(obj, ARRAY_LABEL_PROPERTY, getattr(array, "Label", ""), "String") and tagged
    return tagged


def tag_new_copy_on_change_groups(doc, array, before_names):
    """Tag hidden auto-delete CopyOnChangeGroup objects created after before_names was captured."""
    tagged_count = 0

    for obj in get_document_objects(doc):
        object_name = getattr(obj, "Name", None)
        if not object_name or object_name in before_names:
            continue

        if not (is_copy_on_change_group(obj) and is_auto_delete_link(obj) and is_hidden(obj)):
            continue

        if tag_copy_on_change_group(obj, array):
            tagged_count += 1
            print(f"Tagged CopyOnChangeGroup object for cleanup: {object_name}")

    return tagged_count


def remove_hidden_auto_delete_copy_groups(doc, array=None, remove_untagged=True):
    """Remove orphaned hidden CopyOnChangeGroup objects that are not array children."""
    removed_count = 0

    for obj in get_document_objects(doc):
        object_name = getattr(obj, "Name", None)
        if not object_name:
            continue

        if not (is_copy_on_change_group(obj) and is_auto_delete_link(obj) and is_hidden(obj)):
            continue

        is_tagged_match = array is not None and copy_group_matches_array(obj, array)
        if not is_tagged_match and not remove_untagged:
            continue

        try:
            doc.removeObject(object_name)
            removed_count += 1
            print(f"Removed hidden CopyOnChangeGroup object: {object_name}")
        except Exception as e:
            print(f"Warning: Could not remove hidden CopyOnChangeGroup object '{object_name}': {e}")

    return removed_count


def cleanup_array_before_assignment(doc, array, remove_untagged_copy_groups=True):
    """
    Shrink an array and remove stale generated elements from prior runs.

    Only objects that were array elements before shrinking and are no longer
    referenced by the array after shrinking are removed.
    """
    base_object = get_array_base_object(array)
    previous_names = {element.Name for element in get_array_elements(array)}

    if base_object:
        previous_names.discard(base_object.Name)

    if not set_array_dimensions(array, 1, 1, 1):
        print("Warning: Could not resize array for cleanup; unsupported array property names.")
        return

    doc.recompute()

    remaining_elements = get_array_elements(array)
    remaining_names = {element.Name for element in remaining_elements}
    stale_names = previous_names - remaining_names

    for object_name in sorted(stale_names):
        obj = doc.getObject(object_name)
        if obj is None:
            continue

        try:
            doc.removeObject(object_name)
            print(f"Removed stale array element: {object_name}")
        except Exception as e:
            print(f"Warning: Could not remove stale array element '{object_name}': {e}")

    for element in remaining_elements:
        clear_config_override(element)

    remove_hidden_auto_delete_copy_groups(doc, array, remove_untagged=remove_untagged_copy_groups)

    doc.recompute()


def apply_configs_to_array(config=None):
    """
    Apply configuration variants to array elements.

    Args:
        config: Optional configuration dictionary with keys:
            - spreadsheet_label: Name of the spreadsheet with configs
            - array_label: Name of the array object
    """
    doc = FreeCAD.ActiveDocument
    if not doc:
        print("No active document found.")
        return

    # Use provided config or use defaults
    if config is None:
        config = {
            "spreadsheet_label": "VariantData",
            "array_label": "VariantTestArray",
        }

    spreadsheet_label = config.get("spreadsheet_label", "VariantData")
    array_label = config.get("array_label", "VariantTestArray")
    cleanup_before_assign = config.get("cleanup_before_assign", True)
    cleanup_untagged_copy_groups = config.get("cleanup_untagged_copy_groups", True)
    enable_link_copy_on_change = config.get("enable_link_copy_on_change", True)

    # Retrieve objects by User Label
    spreadsheet = get_object_by_user_label(doc, spreadsheet_label)
    array = get_object_by_user_label(doc, array_label)

    if not spreadsheet:
        print(f"Error: Spreadsheet with user label '{spreadsheet_label}' not found.")
        return
    if not array:
        print(f"Error: Array with user label '{array_label}' not found.")
        return

    # --- 2. GET THE COUNT OF CONFIGS (STARTING AT ROW 2) ---
    configs = []
    current_row = 2  # Start at line 2 (Line 1 is the header)

    while True:
        cell_location = f"A{current_row}"

        try:
            # This will throw a ValueError if the cell is completely uninitialized/empty
            cell_value = spreadsheet.get(cell_location)
        except ValueError:
            # We hit an uninitialized cell, meaning we reached the end of the data
            break
        except Exception as e:
            print(f"Stopped reading spreadsheet at {cell_location} due to unexpected error: {e}")
            break

        # Stop searching when an empty string or None is encountered
        # (in case the cell was initialized/formatted but left blank)
        if cell_value is None or str(cell_value).strip() == "":
            break

        configs.append(normalize_config_name(cell_value))
        current_row += 1

    num_configs = len(configs)

    if num_configs == 0:
        print("No configurations found in column A starting from row 2.")
        return

    print(f"Found {num_configs} configurations: {configs}")

    # --- 3. RESIZE THE ORTHO ARRAY ---
    # Calculate grid size (e.g. 9 -> 3x3, 10 -> 4x3)
    grid_size_x = math.ceil(math.sqrt(num_configs))
    grid_size_y = math.ceil(num_configs / grid_size_x)

    if cleanup_before_assign:
        cleanup_array_before_assignment(doc, array, remove_untagged_copy_groups=cleanup_untagged_copy_groups)

    # Apply to Draft Ortho Arrays or Link Arrays.
    if not set_array_dimensions(array, grid_size_x, grid_size_y, 1):
        print("Error: Unsupported array type. Could not set array dimensions.")
        return

    # Recompute to ensure the array generates/updates the children Link objects
    # based on the new dimension numbers before we try assigning things to them.
    doc.recompute()

    # --- 4. FIND ARRAY ELEMENTS AND APPLY CONFIGS ---
    array_elements = get_array_elements(array)

    if len(array_elements) < num_configs:
        print(f"Warning: Found {len(array_elements)} array elements, but have {num_configs} configurations.")
        print("The array might not be fully generating independent child Links.")

    # --- FORCE ENUMERATION REFRESH ---
    # First, mark the "config" property of all elements as Touched
    for element in array_elements:
        if hasattr(element, "config"):
            try:
                element.setPropertyStatus("config", "Touched")
            except Exception:
                pass

    # Recompute the document so FreeCAD rebuilds the valid Enum list internally
    doc.recompute()

    before_copy_group_names = {getattr(obj, "Name", None) for obj in get_document_objects(doc)}

    # Assign each found element a config string
    for i, config_name in enumerate(configs):
        if i >= len(array_elements):
            break

        element = array_elements[i]

        # 4a. Enable Copy-on-Write so properties can be overridden without modifying the base
        if enable_link_copy_on_change and hasattr(element, "LinkCopyOnChange"):
            element.LinkCopyOnChange = "Enabled"  # standard value in Link branch/FeaturePython links

        # An alternative way copy-on-write is sometimes handled in properties:
        try:
            element.setPropertyStatus("config", "CopyOnChange")
        except Exception:
            pass

        # 4b. Assign the "config" property
        if hasattr(element, "config"):
            element.config = config_name
            print(f"Assigned config '{config_name}' to element: {element.Label}")
        else:
            print(f"Element {element.Label} does not have a property named 'config'.")

    # Final recompute to apply the configuration visual/structural changes
    doc.recompute()
    tag_new_copy_on_change_groups(doc, array, before_copy_group_names)
    print("Array update complete.")


def main():
    """Main entry point - can be called with or without configuration."""
    doc = FreeCAD.ActiveDocument
    if not doc:
        print("No active document.")
        return

    # Check if a config file exists in the document's directory
    doc_path = Path(doc.FileName) if hasattr(doc, "FileName") and doc.FileName else None
    config_path = None
    if doc_path:
        config_dir = doc_path.parent
        config_path = config_dir / ".freecad_tools" / "macro_config.yml"

    # Define dialog fields for user configuration
    dialog_fields = [
        {
            "name": "spreadsheet_label",
            "type": "text",
            "label": "Spreadsheet Name:",
            "default": "VariantData",
            "help": "Name of the spreadsheet containing configurations",
        },
        {
            "name": "array_label",
            "type": "text",
            "label": "Array Name:",
            "default": "VariantTestArray",
            "help": "Name of the array to configure",
        },
        {
            "name": "cleanup_before_assign",
            "type": "checkbox",
            "label": "Clean array before assigning:",
            "default": True,
            "help": "Shrink the array and remove stale generated elements before assigning configurations",
        },
        {
            "name": "enable_link_copy_on_change",
            "type": "checkbox",
            "label": "Enable link copy-on-change:",
            "default": True,
            "help": "Required for each array element to keep an independent configuration",
        },
        {
            "name": "cleanup_untagged_copy_groups",
            "type": "checkbox",
            "label": "Clean untagged CopyOnChangeGroup objects:",
            "default": True,
            "help": "Clean old untagged hidden auto-delete CopyOnChangeGroup objects from earlier macro runs",
        },
    ]

    # Load or prompt for configuration
    config = load_or_prompt_config(
        str(config_path) if config_path else ".freecad_tools/macro_config.yml",
        dialog_fields=dialog_fields,
        dialog_title="Apply Variant Configurations to Array",
    )

    if config:
        apply_configs_to_array(config=config)


# Run the macro
if __name__ == "__main__":
    main()
else:
    # When called via Macro menu, run main directly
    main()
