import FreeCAD
import math

def get_object_by_user_label(doc, user_label):
    """
    Finds an object by the user-editable Label shown in the Tree View.
    """
    matching_objects = doc.getObjectsByLabel(user_label)
    if matching_objects:
        return matching_objects[0] 
    return None

def apply_configs_to_array():
    doc = FreeCAD.ActiveDocument
    if not doc:
        print("No active document found.")
        return

    # --- 1. SET YOUR EXACT TREE VIEW LABELS HERE ---
    spreadsheet_label = "VariantData"       
    array_label = "VariantTestArray"      
    
    # Retrieve objects by User Label
    spreadsheet = get_object_by_user_label(doc, spreadsheet_label)
    array = get_object_by_user_label(doc, array_label)

    if not spreadsheet:
        print(f"Error: Spreadsheet with user label '{spreadsheet_label}' not found.")
        return
    if not array:
        print(f"Error: Array with user label '{array_label}' not found.")
        return

    # --- 2. GET THE COUNT OF CONFIGS (STARTING AT ROW 2) ---
    configs = []
    current_row = 2 # Start at line 2 (Line 1 is the header)
    
    while True:
        cell_location = f'A{current_row}'
        
        try:
            # This will throw a ValueError if the cell is completely uninitialized/empty
            cell_value = spreadsheet.get(cell_location)
        except ValueError:
            # We hit an uninitialized cell, meaning we reached the end of the data
            break
        except Exception as e:
            print(f"Stopped reading spreadsheet at {cell_location} due to unexpected error: {e}")
            break
        
        # Stop searching when an empty string or None is encountered 
        # (in case the cell was initialized/formatted but left blank)
        if cell_value is None or str(cell_value).strip() == '':
            break
            
        configs.append(str(cell_value).strip())
        current_row += 1

    num_configs = len(configs)

    if num_configs == 0:
        print("No configurations found in column A starting from row 2.")
        return
        
    print(f"Found {num_configs} configurations: {configs}")

    # --- 3. RESIZE THE ORTHO ARRAY ---
    # Calculate grid size (e.g. 9 -> 3x3, 10 -> 4x3)
    grid_size_x = math.ceil(math.sqrt(num_configs))
    grid_size_y = math.ceil(num_configs / grid_size_x)
    
    # Apply to Draft Ortho Arrays or Link Arrays
    # It tries the standard properties FreeCAD uses for X/Y counts
    if hasattr(array, "NumberX"):
        array.NumberX = grid_size_x
        array.NumberY = grid_size_y
        if hasattr(array, "NumberZ"): array.NumberZ = 1
    elif hasattr(array, "CountX"):        # Common in Link Branch
        array.CountX = grid_size_x
        array.CountY = grid_size_y
        if hasattr(array, "CountZ"): array.CountZ = 1
    elif hasattr(array, "XQuantity"):
        array.XQuantity = grid_size_x
        array.YQuantity = grid_size_y
        if hasattr(array, "ZQuantity"): array.ZQuantity = 1
    
    # Recompute to ensure the array generates/updates the children Link objects 
    # based on the new dimension numbers before we try assigning things to them.
    doc.recompute()

    # --- 4. FIND ARRAY ELEMENTS AND APPLY CONFIGS ---
    base_object = getattr(array, "Base", getattr(array, "Source", None))
    
    # Collect the individual link elements generated by the array
    array_elements = []
    
    # Check if elements are standard children/group items (Most common for LinkArrays / LinkGroups)
    if hasattr(array, "OutList"):
        for child in array.OutList:
            # We want to grab the array children but NOT the base original object
            if base_object and child.Name == base_object.Name:
                continue
            array_elements.append(child)
            
    # Fallback if the elements are stored in a Group property
    elif hasattr(array, "Group"):
        for child in array.Group:
            if base_object and child.Name == base_object.Name:
                continue
            array_elements.append(child)

    if len(array_elements) < num_configs:
        print(f"Warning: Found {len(array_elements)} array elements, but have {num_configs} configurations.")
        print("The array might not be fully generating independent child Links.")

    # --- FORCE ENUMERATION REFRESH ---
    # First, mark the "config" property of all elements as Touched
    for element in array_elements:
        if hasattr(element, "config"):
            try:
                element.setPropertyStatus("config", "Touched")
            except Exception:
                pass
                
    # Recompute the document so FreeCAD rebuilds the valid Enum list internally
    doc.recompute()

    # Assign each found element a config string
    for i, config_name in enumerate(configs):
        if i >= len(array_elements):
            break 
            
        element = array_elements[i]
        
        # 4a. Enable Copy-on-Write so properties can be overridden without modifying the base
        if hasattr(element, "LinkCopyOnChange"):
            element.LinkCopyOnChange = 'Enabled' # standard value in Link branch/FeaturePython links
        
        # An alternative way copy-on-write is sometimes handled in properties:
        try:
            element.setPropertyStatus("config", "CopyOnChange")
        except:
            pass
            
        # 4b. Assign the "config" property
        if hasattr(element, "config"):
            element.config = config_name
            print(f"Assigned config '{config_name}' to element: {element.Label}")
        else:
            print(f"Element {element.Label} does not have a property named 'config'.")

    # Final recompute to apply the configuration visual/structural changes
    doc.recompute()
    print("Array update complete.")

# Run the macro
apply_configs_to_array()
