#!/usr/bin/env python3
"""Utilities for Bill of Materials (BOM) CSV generation.

This module handles writing BOM data extracted from FreeCAD documents
to CSV files. Runs in the project venv (not freecadcmd).
"""

import csv
import json
import logging
import sys

logger = logging.getLogger(__name__)


def write_bom_csv(bom_data, output_file, fields=None):
    """
    Write BOM data to CSV file.

    Args:
        bom_data: List of BOM item dicts (from extract_bom_* functions)
        output_file: Path to output CSV file
        fields: List of field names to include in CSV (default: from first item)

    Returns:
        True if successful, False otherwise
    """
    try:
        # Ensure fields always has at least label and quantity
        default_fields = ["label", "quantity"]

        # Determine field list if not provided
        if fields is None:
            # Use fields from all items
            fields = []
            seen_fields = set()
            for item in bom_data:
                for key in item.keys():
                    if key not in seen_fields:
                        fields.append(key)
                        seen_fields.add(key)
            # If no fields found in data and no custom fields, use defaults
            if not fields:
                fields = default_fields
        else:
            # Ensure 'label' and 'quantity' are always included
            for field in default_fields:
                if field not in fields:
                    fields.insert(default_fields.index(field), field)

        logger.debug(f"CSV fields: {fields}")

        # Write CSV file (always write, even if bom_data is empty - this ensures
        # a CSV file is created for PDF generation to reference)
        with open(output_file, "w", newline="", encoding="utf-8") as csvfile:
            writer = csv.DictWriter(csvfile, fieldnames=fields, restval="")
            writer.writeheader()

            for item in bom_data:
                # Ensure all fields are present in the row (use empty string as fallback)
                row = {field: item.get(field, "") for field in fields}
                writer.writerow(row)

        logger.info(f"Wrote BOM CSV with {len(bom_data)} items to: {output_file}")
        return True

    except Exception as e:
        logger.exception(f"Error writing BOM CSV: {e}")
        return False


def create_bom_from_json_config(json_config_file, output_file):
    """
    Create BOM CSV from JSON config generated by fc_export.py.

    The JSON config contains BOM data and field specifications.

    Args:
        json_config_file: Path to JSON file from freecadcmd subprocess
        output_file: Path to output CSV file

    Returns:
        True if successful, False otherwise
    """
    try:
        # Read JSON config
        with open(json_config_file) as f:
            config = json.load(f)

        bom_data = config.get("bom_data", [])
        fields = config.get("fields", None)

        logger.debug(f"Loaded BOM config: {len(bom_data)} items, fields: {fields}")

        # Write CSV
        return write_bom_csv(bom_data, output_file, fields=fields)

    except Exception as e:
        logger.exception(f"Error creating BOM from JSON config: {e}")
        return False


def main():
    """CLI interface for BOM CSV generation."""
    if len(sys.argv) < 3:
        print("Usage: bom_utils.py <json_config_file> <output_csv_file> [fields...]")
        sys.exit(1)

    json_config = sys.argv[1]
    output_csv = sys.argv[2]

    # Configure logging
    logging.basicConfig(
        level=logging.INFO,
        format="%(name)s - %(levelname)s - %(message)s",
        handlers=[
            logging.FileHandler("bom_utils.log"),
            logging.StreamHandler(sys.stderr),
        ],
    )

    success = create_bom_from_json_config(json_config, output_csv)
    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()
